exclude: |
  (?x)^(
      ^helm-charts/.+\.yaml$
  )$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.3
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]

  # Local hooks that rely on the project environment.
  - repo: local
    hooks:
      - id: pytest-with-coverage-via-uv
        name: Run pytest with coverage via uv
        entry: bash
        language: system
        args:
          - -c
          - uv run coverage run -m pytest && uv run coverage report -m
        pass_filenames: false
        stages: [commit]
